name: build_experimental

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["cache layers"]
    types: 
    - completed

env:
  BUILDDIR: experimental

jobs:
  prepare:
    runs-on: [self-hosted, linux, x64, builder]
    steps:
      - name: Clean up
        run: rm -fR $BUILDDIR
      - uses: actions/checkout@v4

  build:
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        board: [
          olimex-imx8mp-evb,
          jetson-agx-orin-devkit,
          jetson-agx-xavier-devkit,
          jetson-orin-nano-devkit,
          imx93-var-som
        ]
        subpath: [.]

    runs-on: [self-hosted, linux, x64, builder]
    container:
      # the container image needs to be effectively hardcoded, it seems.
      image: ghcr.io/theyoctojester/devcontainer-base-yoep:main
      volumes:
        - ${{ vars.PERSISTENT_DIR }}/downloads:${{ vars.BUILD_DL_DIR }}
        - ${{ vars.PERSISTENT_DIR }}/sstate-cache:${{ vars.BUILD_SSTATE_DIR }}
        - ${{ vars.PERSISTENT_DIR }}/layers:${{ vars.BUILD_LAYERCACHE_DIR }}
        - ${{ vars.PERSISTENT_DIR }}/assets:${{ vars.BUILD_ASSETS_DIR }}
      options: --user ${{ vars.KAS_UID }}:${{ vars.KAS_GID }}
    steps:
      - name: enter build dir and build
        env:
          DL_DIR: ${{ vars.BUILD_DL_DIR}}
          SSTATE_DIR: ${{ vars.BUILD_SSTATE_DIR}}
          KAS_REPO_REF_DIR: ${{ vars.BUILD_LAYERCACHE_DIR}}
        run: >
          mkdir -p $BUILDDIR/${{ matrix.board }} &&
          cd $BUILDDIR/${{ matrix.board }} &&
          kas checkout ../../kas/${{ matrix.subpath }}/${{ matrix.board }}.yml &&
          if [ -f "${{ vars.BUILD_ASSETS_DIR }}/site.conf" ]; then 
          cp ${{ vars.BUILD_ASSETS_DIR }}/site.conf build/conf/site.conf;
          fi &&
          kas build ../../kas/${{ matrix.subpath }}/${{ matrix.board }}.yml
