name: cache_layers

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 2 * * 6'

jobs:
  prepare:
    runs-on: [self-hosted, linux, x64, builder]
    steps:
      - name: cache metadata layers
        run: ./ci/update-repos
        env:
          LAYERCACHE: ${{ vars.PERSISTENT_DIR }}/layers
